blank_issues_enabled: false

contact_links:
  - name: GitHub Discussions
    url: https://github.com/doddleOS/doddleOS-marketing/discussions
    about: Ask questions and discuss with the community

  - name: Documentation
    url: https://docs.doddlehq.com
    about: Read the documentation for answers

  - name: Training
    url: https://github.com/doddleOS/doddleOS-marketing/tree/main/training
    about: Learn Doddle Marketing OS with our training modules
